name: Run Tests for Server

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests in Server Folder

    steps:
      # Check out the code
      - uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install dependencies
      - name: Install Dependencies
        working-directory: server
        run: npm install

      # Run tests
      - name: Run Tests
        working-directory: server
        run: npm run test
