name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -U test_user -d test_db; do
            sleep 1;
          done

      - name: Run migrations (if required)
        run: |
          npx knex migrate:latest

      - name: Run tests
        env:
          PORT : 3001
          DB_USER : test_user
          DB_HOST: 127.0.0.1
          DB_NAME : test_db
          DB_PASSWORD: test_password
          DB_PORT : 5432
          JWT_SECRET_KEY : asdfasdfkajehfkew
          TMDB_API_KEY: 6e9e4df1f8d6a6a540ccf27bb6efc253
          EMAIL_USER : techbloganil@gmail.com
          EMAIL_PASS : zvpd gizv nyxo dusc
        run: npm test
